services:
  app:
    build:
      context: .
    ports:
      - ":5000"

    volumes:
      - ./.aws:/root/.aws:ro
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    depends_on:
      - app

    ports:
      - "80:80"